### ISSUE TITLE
No module named 'paho'

### ISSUE THREAD

**Issue by mauriceatkinson** [dalehumby/PiJuice-MQTT#1]
Hi
I tried to install your code but I get the following error when I try to run pijuicemqtt.py:

pi@unit002:~/PiJuice-MQTT $ sudo python3 pijuicemqtt.py
Traceback (most recent call last):
  File "pijuicemqtt.py", line 12, in <module>
    import paho.mqtt.client as mqtt
ModuleNotFoundError: No module named 'paho'

**Comment by mauriceatkinson** [comment]
@dalehumby

**Comment by dalehumby** [comment]
Hi @mauriceatkinson 

I initially thought this was because I am using version 1.5.0 of paho-mqtt, but I have now upgraded to the latest version 1.6.1 and it works fine for me.

If you look at the [Getting Started](https://pypi.org/project/paho-mqtt/#usage-and-api) the example also shows `import paho.mqtt.client as mqtt`. 

I also tried running with and without `sudo`, thinking it was something to do with the version of Python.

Did you run the step: `pip install -r requirements.txt`?

Looking at my docs now, I think it should be `pip3 install -r requirements.txt` Note **`pip3`**, and not just `pip`. 

Could you try pip3 install and see if that fixes the issue?
